name: PowerShell - Script Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  script-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run Script Analyzer
        shell: pwsh
        run: |
          Write-Host "Using repo settings file if present: .PSScriptAnalyzerSettings.psd1"
          Invoke-ScriptAnalyzer -Path . -Recurse
